export const TranslationEn = {
    Home:"Home",
    loginText:"Please, provide login credential to proceed and have access to all our services",
    UserName:"User Name",
    Password:"Password",
    buttonText:"Login",
    Company:"Dire Dawa Adminstration",
    Software:"Property managment System",
    LNG:"English",
    Stock:"Stock",
    Information:"Information",
    Employee:"Employee",
    pro:"Property",
    Property:"Property Information",
    propertyI:"Property Registration",
    Income:"Income",
    Fixed:"Fixed asset",
    PropertyII:"Rare Item",
    propertyIII:"Used Prorpert",
    Adjustment:"Adjusment",
    Cost:"Cost",
    Setting:"Setting",
    Manual:"Manual",
    InformationRegister:"Record information",
    CategorySource :"Category source  funding",
    IdentificationNumber:"Identification number",
    PropertyInventory:"Property Inventory",
    InventoryFixedAssets:"Inventory fixed assets",
    FAOU:"Fixed assets of users",
    FAOUIC:"Fixed assets of users I&C",
    FAOUC:"Inventory users property",
    FAOUS:"Fixed asset discount rate",
    FAOUM:"Fixed asset account report",
    OrganizationIstitution:"Organization Institution",
    Propertyclassification:"Property measurement",
    Costcenters:"Cost Center",
    vechiles:"Vechiles",
    NewVechiles:"New Vechiles",
    Vehiclelist:"Vechiles List",
    Report:"Report",
    Details:"Detail",
    Logout:"Logout",
    EmployeeList:"Employee Information List",
    NewEmployee:" Add New Employee ",
    Order:"Order",
    EmployeePhoto:"Employee Picture",
    ID:"Id Number",
    FullName:"FullName",
    Gender:"Gender",
    WorkClass:"Work Class",
    WorkRoom:"Work Room",
    Action:"ተግባራት"
    };
    export const TranslationAm = {
        loginText:"እባኮትን ለመቀጠል እና ሁሉንም አገልግሎቶቻችንን ለማግኘት ኢሜል እና የዪለፍ ቃል ያስገቡ",
        UserName:"ኢሜል",
        Password:"የዪለፍ ቃል",
        buttonText:"ግባ",
        Company:"የድሬዳዋ አስተዳደር",
        Software:"የንብረት አስተዳደር መተግበሪያ",
        Home:"እንኮን ደና መጡ",
        LNG:"ቆንቆ",
        Stock:"ስቶክ",
        Setting:"ቅንብሮች",
        Information:"መረጃ",
        Employee:"ሰራተኛ",
        pro:"ንብረት",
        Property:"ንብረት መረጃ መመዝገቢያ",
        PropertyI:"ንብረት መመዝገቢያ",
        Income:"ገቢ ንብረት",
        Fixed:"ቆሚ ንብረት",
        PropertyII:"አላቂ ንብረት",
        propertyIII:"ያገለገለ ንብረት",
        Adjustment:"ማስተካከያ",
        Cost:"ወጪ ንብረት",
        Manual:"መመሪያ",
        InformationRegister:"መረጃ ምዝገባ",
        CategorySource :"ምድብና የገንዘብ ምንጭ",
        IdentificationNumber:"መለያ ቁጥር",
        InventoryFixedAssets:"ቆሚ ንብረት ቆጠራ",
        PropertyInventory:"ንብረት ቆጠራ",
        FAOU:"የተጠቃሚዎች ቆሚ ንብረት ",
        FAOUIC:"የተጠቃሚዎች ቆ/ን ገቢ/ወጪ ",
        FAOUC:"የተጠቃሚዎች ንብረት ቆጠራ ",
        FAOUS:"ቆ/ን ቅናሽ መጠን ",
        FAOUM:"ቆ/ን ምድብ የሒ/ረፖርት ",
        OrganizationIstitution:"ተቋም አደረጃጀት",
        Propertyclassification:"ንብረት መድብና መለኪያ",
        Costcenters:"ወጪ ማእከላት",
        vechiles:"ተሽከርካሪ",
        NewVechiles:"አዲስ ተሽከርካሪ",
        Vehiclelist:"ተሽክርካሪ ዝርዝር",
        Report:"ሪፖርት",
        Details:"ዝርዝር",
        Logout:"ውጣ",
        EmployeeList:"የሰራተኛ መርጃ መዝገቦች ዝርዝር",
        NewEmployee:" አዲስ ሰራተኛ መዝግብ",
        Order:"ተራ",
        EmployeePhoto:"ሰራተኛ ፎቶ",
        ID:"የመታወቂያ ቁጥር",
        FullName:"ሙሉ ስም",
        Gender:"ጾታ",
        WorkClass:"የስራ መደብ",
        WorkRoom:"የስራ ክፍል",
        Action:"ተግባራት"
         };
    