export const TranslationEn = {
  Home: "Home",
  loginText:
    "Please, provide login credential to proceed and have access to all our services",
  UserName: "User Name",
  Password: "Password",
  buttonText: "Login",
  Company: "Dire Dawa Adminstration",
  Software: "Property managment System",
  LNG: "Lang",
  Organization: "Organization",
  Structure: "Structure",
  Office: "Office",
  Department: "Department",
  DepartmentType: "Department Type",
  NewDepartment: "Add New Departmnet",
  RegisterdDepartment: "Department List",
  NewDepartmentType: "Add New Departmnet Type",
  RegisterdDepartmentType: "Department List Type",
  Stock: "Stock",
  Information: "Information",
  Employee: "Employee",
  pro: "Property",
  Property: "Property Information",
  propertyI: "Property Registration",
  Income: "Income",
  Fixed: "Fixed asset",
  PropertyII: "Rare Item",
  propertyIII: "Used Prorpert",
  Adjustment: "Adjusment",
  Cost: "Cost",
  Setting: "Setting",
  Manual: "Manual",
  InformationRegister: "Record information",
  CategorySource: "Category source  funding",
  IdentificationNumber: "Identification number",
  PropertyInventory: "Property Inventory",
  InventoryFixedAssets: "Inventory fixed assets",
  FAOU: "Fixed assets of users",
  FAOUIC: "Fixed assets of users I&C",
  FAOUC: "Inventory users property",
  FAOUS: "Fixed asset discount rate",
  FAOUM: "Fixed asset account report",
  OrganizationIstitution: "Organization Institution",
  Propertyclassification: "Property measurement",
  Costcenters: "Cost Center",
  vechiles: "Vechiles",
  NewVechiles: "New Vechiles",
  Vehiclelist: "Vechiles List",
  Report: "Report",
  Details: "Detail",
  Logout: "Logout",
  EmployeeList: "Employee Information List",
  NewEmployee: " Add New Employee ",
  NewEmployeeRegistration: "New Employee Registration Form",
  Order: "Order",
  EmployeePhoto: "Employee Picture",
  ID: "Id Number",
  FullName: "FullName",
  Gender: "Gender",
  WorkClass: "Work Class",
  WorkRoom: "Work Room",
  Action: "Action",
  Find: "Find",
  FindPlaceHolder: "Employe Name",
  FirstName: "First Name",
  MiddleName: "Middle Name",
  LastName: "Last Name",
  PhoneNumber: "ስልክ ቁጥር",
  Mobile: "ሞባይል",
  Email: "ኢሜል",
  Address: "አድራሻ",
  CostCenterName: "Cost Center Name",
  CostCenters: "Select Cost Center",
  WorkPlaceName: "Work Place Name",
  WorkPostion: "Work Position",
  Male: "Male",
  Female: "Female",
  Registor: "Save",
  Cancle: "Cancle",
  WorkPlaces: "Select Work Place",
  NewPropertyRegistration: "New Property Registration",
  Propertycategory: "Property Category",
  PropertySubcategory: "Property Sub Category",
  PropertyType: "Property Type",
  PropertyCode: "Property Code",
  IdentityNumber: "Property ID",
  Model: "Model",
  ShelfNumber: "Shelf Number",
  Price: "Price",
  MinValue: "Minmum Value",
  MaxValue: "Maxmum Value",
  ExpireDate: "Expire Date",
  Describtion: "Describtion",
  ItemPicture: "Property Image",
  Mesurment: "Mesurment",
  ItemType: "Property Class",
  VechilesType: "Vehicle type",
  vechilesModel: "Made In (Model)",
  VechilesYear: "Manufacterd Date",
  VechilesMoterNumber: "Engine number",
  VechilesSilnder: "Cylinder",
  VechilesChasi: "Chassis number",
  VechilesPlateNumber: "Plate number",
  VechilesDateOfPurchase: "Date of purchase",
  VechilesCapacity: "Load capacity",
  CurrentStateOfVechile: "Current State of The Vehicle",
  VechileOwenerIdNumber: "Owner Card Id Number ",
  TypeofGas: "የሚጠቀመው የነዳጅ አይነት",
  NewVechilesRegistrationPage: "New Vehiles Registration Page",
  Code: "Code",
  OfficeList: "Office List",
  AddNewOffice: "Add New Office",
  PropertyMList: "Property Measurment List",
  NewPropertyMList: "New class Register",
  Name: "Classification Name",
  Description: "Description",
  StokeMain: "Stoke",
  StokeMainList: "Stoke List",
  StokeMainReg: "Add New Stock",
  StokeName: "Stoce Name",
  StokeDesc: "Description",
  Type: "Type",
  subStoke: "Subclassification of Stock",
  stokeMeasurment: "Measurment",
  reciver: "Reciver",
  Date: "Date",
  FixedAssetCosting: "Fixed Asset Expense Report",
  CostType: "Cost Type",
  Treasuryexpert: "Treasury Expert",
  Model22U: "Model 22ሀ",
  CompanyFullName: "Dire Dawa Adminstration Office",
  Comment: "Comment",
  CostCenter: "Cost Center",
  Quantity: "Quantity",
  CreateNew22Model: "Create New 22ለ Model",
  AccountsPayableReceipt: "Accounts Payable Receipt Model 22ለ Detiles",
  deliverer: "Deliverer",
  FileNumber: "File Number",
  OfficeName: "Office Name",
  RegisteredDate: "Registered Date",
  back: "Back",
  OfficeType: "Office Type",
};
export const TranslationAm = {
  OfficeType: "የቢሮ አይነት",
  back: "ተመለስ",
  RegisteredDate: "የተመዘገበበት ቀን",
  OfficeName: "የቢሮ ስም",
  CreateNew22Model: "አዲስ ሞዴል 22ለ አዘጋጅ",
  AccountsPayableReceipt: "አላቂ ንብረትና የሂሳብ መዝገቦች ወጪ ማድረጊያ ደረሰኝ [ሞደል 22ለ] ዝርዝር",
  deliverer: "አስረካቢ",
  FileNumber: "የሰነድ ቁጥር",
  CostCenter: "የወጪ ማእከል",
  CompanyFullName: "የድሬዳዋ አስተዳደር ጽ/ቤት",
  FixedAssetCosting: "የቆሚ ንብረት ወጪ ማድረጊያ ደርሰኝ",
  CostType: "የወጪ አይነት",
  Model22U: "ሞዴል 22ሀ",
  reciver: "ተረካቢ",
  Date: "ቀን",
  Treasuryexpert: "የግምጃ ቤት ባለሞያ",
  Comment: "አስተያየት",
  Quantity: "ብዛት",
  Home: "መነሻ",
  loginText: "እባኮትን ለመቀጠል እና ሁሉንም አገልግሎቶቻችንን ለማግኘት ኢሜል እና የዪለፍ ቃል ያስገቡ",
  UserName: "ኢሜል",
  Password: "የይለፍ ቃል",
  buttonText: "ግባ",
  Company: "የድሬዳዋ አስተዳደር",
  Software: "የንብረት አስተዳደር መተግበሪያ",
  Home: "እንኮን ደና መጡ",
  LNG: "ቋንቋ",
  Organization: "ተቆማት",
  Structure: "የተቆማት አወቃቀር",
  Office: "ቢሮ",
  Department: "የስራ ክፍል",
  DepartmentType: "የስራ ክፍል አይነት",
  NewDepartment: "አዲስ የስራ ሂደት መመዝገቢያ",
  NewDepartmentType: "አዲስ የስራ  ክፍል አይነት መመዝገቢያ",
  RegisterdDepartment: "የተመዘገቡ የስራ ክፍሎች",
  RegisterdDepartmentType: "የተመዘገቡ የስራ ክፍሎች አይነቶች",
  Stock: "ስቶክ",
  Setting: "ቅንብሮች",
  Information: "መረጃ",
  Employee: "ሰራተኛ",
  pro: "ንብረት",
  Property: "ንብረት መረጃ መመዝገቢያ",
  PropertyI: "ንብረት መመዝገቢያ",
  Income: "ገቢ ንብረት",
  Fixed: "ቆሚ ንብረት",
  PropertyII: "አላቂ ንብረት",
  propertyIII: "ያገለገለ ንብረት",
  Adjustment: "ማስተካከያ",
  Cost: "ወጪ ንብረት",
  Manual: "መመሪያ",
  InformationRegister: "መረጃ ምዝገባ",
  CategorySource: "ምድብና የገንዘብ ምንጭ",
  IdentificationNumber: "መለያ ቁጥር",
  InventoryFixedAssets: "ቆሚ ንብረት ቆጠራ",
  PropertyInventory: "ንብረት ቆጠራ",
  FAOU: "የተጠቃሚዎች ቆሚ ንብረት ",
  FAOUIC: "የተጠቃሚዎች ቆ/ን ገቢ/ወጪ ",
  FAOUC: "የተጠቃሚዎች ንብረት ቆጠራ ",
  FAOUS: "ቆ/ን ቅናሽ መጠን ",
  FAOUM: "ቆ/ን ምድብ የሒ/ረፖርት ",
  OrganizationIstitution: "ተቋም አደረጃጀት",
  Propertyclassification: "ንብረት መድብና መለኪያ",
  Costcenters: "ወጪ ማእከላት",
  vechiles: "ተሽከርካሪ",
  NewVechiles: "አዲስ ተሽከርካሪ",
  Vehiclelist: "ተሽክርካሪ ዝርዝር",
  Report: "ሪፖርት",
  Details: "ዝርዝር",
  Logout: "ውጣ",
  EmployeeList: "የሰራተኛ መርጃ መዝገቦች ዝርዝር",
  NewEmployee: " አዲስ ሰራተኛ መዝግብ",
  NewEmployeeRegistration: " አዲስ ሰራተኛ መረጃ መመዝገቢያ ቅጽ",
  Order: "ተራ",
  EmployeePhoto: "ሰራተኛ ፎቶ",
  ID: "የመታወቂያ ቁጥር",
  FullName: "ሙሉ ስም",
  Gender: "ጾታ",
  WorkClass: "የስራ መደብ",
  WorkRoom: "የስራ ክፍል",
  Action: "ተግባራት",
  Find: "ፈልግ",
  FindPlaceHolder: "የሰራተኛ ስም",
  FirstName: "ስም",
  MiddleName: "የአባት ስም",
  LastName: "የአያት ስም",
  PhoneNumber: "ስልክ ቁጥር",
  Mobile: "ሞባይል",
  Email: "ኢሜል",
  Address: "አድራሻ",
  CostCenterName: "የወጪ ማእከል ስም",
  CostCenters: "የወጪ ማእከል ይምረጡ",
  WorkPlaceName: "የስራ ቦታ ስም",
  WorkPostion: "የስራ መደብ",
  Male: "ወንድ",
  Female: "ሴት",
  Registor: "ይመዝገብ",
  Cancle: "መሰረዝ",
  WorkPlaces: "የስራ ቦታ የምረጡ",
  NewPropertyRegistration: "አዲስ ንብረት መረጃ መመዝገቢያ ቅጽ",
  Propertycategory: "የንብረት ምድብ",
  PropertySubcategory: "የንብረት ንኡስ ምድብ",
  PropertyType: "የእቃው አይነት",
  PropertyCode: "ለንብረቶች የተሰጠ ኮድ",
  IdentityNumber: "መለያ ቁጥር",
  Model: "ሞዴል",
  ShelfNumber: "ግምጃ ቤት (ሼልፍ ቁጥር)",
  Price: "ዋጋ",
  MinValue: "ዝቅተኛ መጠን",
  MaxValue: "ከፍተኛ መጠን",
  ExpireDate: "የመበላሻ ቀን",
  Describtion: "ማብራሪያ",
  ItemPicture: "የእቃው ምስል",
  Mesurment: "መለኪያ",
  ItemType: "የእቃው ምድብ",
  VechilesType: "የተሽከርካሪ አይነት",
  vechilesModel: "የተስራበት ሃገር (ሞዴል)",
  VechilesYear: "የተሰራበት አመት",
  VechilesMoterNumber: "የሞተር ቁጥር",
  VechilesSilnder: "ሲልንደር",
  VechilesChasi: "የቻሲ ቁጥር",
  VechilesPlateNumber: "የሰሌዳ ቁጥር",
  VechilesDateOfPurchase: "የተገዛበት ቀን",
  VechilesCapacity: "የመጫን አቅም",
  CurrentStateOfVechile: "ተሽከርካሪው አሁን ያለበት ሁኔታ",
  VechileOwenerIdNumber: "የባለቤትነት መታወቂያ ደፕተር ቁጥር",
  TypeofGas: "የሚጠቀመው የነዳጅ አይነት",
  NewVechilesRegistrationPage: "አዲስ ተሽከርካሪ መርጃ መመዝገቢያ ቅጽ",
  Code: "መለያ",
  OfficeList: "የተመዘገቡ ቢሮዎች",
  AddNewOffice: "አዲስ ቢሮ መመዝገቢያ",
  PropertyMList: "የስቶክ አስተዳደር",
  NewPropertyMList: "አዲስ",
  Name: "የምድቡ ስም",
  Description: "መግለጫ",
  StokeMain: "የስቶክ ምድብ",
  StokeMainList: "የተመዘገቡ ስቶክ ምድብ ዝርዝር",
  StokeMainReg: "የስቶክ ምድብ መመዝገቢያ",
  StokeName: "ምደባ ስያሜ",
  StokeDesc: "መግለጫ",
  Type: "አይንት",
  subStoke: "ንኡስ ስቶክ ምድብ",
  stokeMeasurment: "መለኪያ",
};
export const TranslationOr = {
  RegisterdDepartmentType: "Gosa Tarree Kutaa Kutaa",
  NewDepartmentType: "Gosa Kutaa Haaraa Dabaluu",
  NewDepartment: "Kutaa Haaraa Dabaluu",
  RegisterdDepartment: "Tarree Kutaa Kutaa",
  DepartmentType: "Gosa Kutaa",
  Department: "Qajeelcha",
  Office: "Waajjira",
  OfficeType: "Gosa Waajjira",
  back: "dugda",
  RegisteredDate: "Guyyaa Galmaa'e",
  CreateNew22Model: "Moodeela 22L Haaraa Uumuu",
  AccountsPayableReceipt: "Nagahee Herrega Kaffaltii Moodeela 22L Bal’ina",
  deliverer: "Dhiyeessaa",
  FileNumber: "Lakkoofsa Faayilii",
  CostCenter: "Giddugala Baasii",
  reciver: "fudhataa",
  Date: "Guyyaa",
  FixedAssetCosting: "Gabaasa Baasii Qabeenya Dhaabbataa",
  CostType: "Gosa Baasii",
  Treasuryexpert: "Ogeessa Tiraazirarii",
  Model22U: "Adda duree 22A",
  CompanyFullName: "Waajjira Bulchiinsa Dire Dawaa",
  Comment: "Yaada kennuu",
  Quantity: "Baay'ina",
  Home: "mana",
  loginText:
    "Maaloo, itti fufuu fi tajaajila keenya hunda argachuuf ragaa seensaa kenni",
  UserName: "Maqaa Fayyadamaa",
  Password: "Jecha iccitii",
  buttonText: "Galmaa'i",
  Company: "Bulchiinsa Dire Dawaa",
  Software: "Sirna bulchiinsa qabeenyaa",
  LNG: "Afaan",
  Stock: "Kuusaa",
  Information: "Odeeffannoo",
  Employee: "Qacaramaa",
  pro: "Qabeenya",
  Property: "Odeeffannoo Qabeenyaa",
  propertyI: "Galmee Qabeenyaa",
  Income: "Galii",
  Fixed: "Qabeenya dhaabbataa",
  PropertyII: "Meeshaa Harka Hin Qabne",
  propertyIII: "Qabeenya Fayyadamaa",
  Adjustment: "Sirreeffama",
  Cost: "Baasii",
  Setting: "Haala",
  Manual: "Kan harkaanii",
  InformationRegister: "Odeeffannoo galmeessi",
  CategorySource: "Madda gosa maallaqaa",
  IdentificationNumber: "Lakkoofsa eenyummaa",
  PropertyInventory: "Inventarii Qabeenyaa",
  InventoryFixedAssets: "Qabeenya dhaabbataa inventarii",
  FAOU: "Qabeenya dhaabbataa fayyadamtootaa",
  FAOUIC: "Qabeenya dhaabbataa fayyadamtootaa I&C",
  FAOUC: "Qabeenya fayyadamtoota inventarii",
  FAOUS: "Sadarkaa hir’ina qabeenya dhaabbataa",
  FAOUM: "Gabaasa herrega qabeenya dhaabbataa",
  OrganizationIstitution: "Dhaabbata Jaarmiyaa",
  Propertyclassification: "Safartuu qabeenyaa",
  Costcenters: "Giddugala Baasii",
  vechiles: "Konkolaataa",
  Details: "Gadi fageenya",
  Logout: "Ba'i",
  EmployeeList: "Tarree Odeeffannoo Hojjetaa",
  NewEmployee: " Hojjetaa Haaraa Dabaluu",
  NewEmployeeRegistration: "Unka Galmee Hojjetaa Haaraa",
  Order: "Ajajuu",
  EmployeePhoto: "Suuraa Hojjetaa",
  ID: "Lakkoofsa Id",
  FullName: "Maqaa Guutuu",
  Gender: "Koorniyaa",
  WorkClass: "Gitaa Hojii",
  WorkRoom: "Kutaa Hojii",
  Action: "Gocha",
  Find: "Argachuu",
  FindPlaceHolder: "Maqaa Hojjetaa",
  FirstName: "Maqaa jalqabaa",
  MiddleName: "Maqaa Giddugaleessaa",
  LastName: "Maqaa akaakayyuu",
  PhoneNumber: "Lakkoofsa Bilbilaa",
  Mobile: "Sochootuu",
  Email: "Imeelii",
  Address: "Teessoo",
  CostCenterName: "Maqaa Giddugala Baasii",
  CostCenters: "Giddugala Baasii filadhu",
  WorkPlaceName: "Maqaa Bakka Hojii",
  WorkPostion: "Iddoo Hojii",
  Male: "Dhiira",
  Female: "Dhalaa",
  Registor: "Qusachuu",
  Cancle: "Cancle gochuu",
  WorkPlaces: "Bakka Hojii filadhu",
  NewPropertyRegistration: "Galmee Qabeenya Haaraa",
  Propertycategory: "Ramaddii Qabeenyaa",
  PropertySubcategory: "Qabeenya Sub Category",
  PropertyType: "Gosa Qabeenyaa",
  PropertyCode: "Seera Qabeenyaa",
  IdentityNumber: "ID Qabeenyaa",
  Model: "Adda duree",
  ShelfNumber: "Lakkoofsa Sheelfii",
  Price: "Gatii",
  MinValue: "Gatii Xiqqaa",
  MaxValue: "Gatii Ol'aanaa",
  ExpireDate: "Guyyaa Xumuraa",
  Describtion: "Ibsa",
  ItemPicture: "Fakkii Qabeenyaa",
  Mesurment: "Safartuu",
  ItemType: "Gita Qabeenyaa",
  VechilesType: "Gosa konkolaataa",
  vechilesModel: "Kan Hojjetame (Modeela) .",
  VechilesYear: "Guyyaa Oomishame",
  VechilesMoterNumber: "Lakkoofsa motoraa",
  VechilesSilnder: "Siilindara",
  VechilesChasi: "Lakkoofsa chaasii",
  VechilesPlateNumber: "Lakkoofsa gabatee",
  VechilesDateOfPurchase: "Guyyaa bittaa",
  VechilesCapacity: "Dandeettii fe’umsaa",
  CurrentStateOfVechile: "Haala Yeroo Ammaa Konkolaataan",
  VechileOwenerIdNumber: "Lakkoofsa Id Kaardii Abbaa Qabeenyaa",
  TypeofGas: "Gosa boba’aa itti fayyadamnu",
  NewVechilesRegistrationPage: "Fuula Galmee Konkolaataa Haaraa",
  OfficeName: "Maqaa Waajjira",
  Code: "Koodii",
  OfficeList: "Tarree Waajjiraalee",
  AddNewOffice: "Waajjira Haaraa Dabaluu",
  PropertyMList: "Tarree Safartuu Qabeenyaa",
  NewPropertyMList: "Daree haaraa Galmaa'i",
  Name: "Maqaa Ramaddii",
  Description: "Ibsa",
  StokeMain: "Istookii",
  StokeMainList: "Tarree Istookii",
  StokeMainReg: "Istookii Haaraa Dabaluu",
  StokeName: "Maqaa Iddoo ibiddaa",
  StokeDesc: "Ibsa",
  Type: "Akaakuu",
  subStoke: "Ramaddii xiqqaa Istookii",
  stokeMeasurment: "Safartuu",
};
export const TranslationTi = {
  RegisterdDepartmentType: "ዓይነት ዝርዝር ክፍሊ",
  NewDepartmentType: "ሓድሽ ዓይነት ክፍሊ ምውሳኽ",
  NewDepartment: "ሓድሽ ክፍሊ ምውሳኽ",
  RegisterdDepartment: "ዝርዝር ክፍልታት",
  DepartmentType: "ዓይነት ክፍሊ",
  Department: "ክፍሊ",
  Office: "ቤት-ፅሕፈት",
  OfficeType: "ዓይነት ቤት ጽሕፈት",
  back: "ዝባን",
  RegisteredDate: "ዝተመዝገበበት ዕለት",
  CreateNew22Model: "ሓድሽ 22ለ ሞዴል ​​ምፍጣር",
  AccountsPayableReceipt: "ሒሳብ ዝኽፈል ቅብሊት ሞዴል 22ለ ዝርዝር",
  deliverer: "ኣቕራቢ",
  FileNumber: "ቁጽሪ ፋይል",
  CostCenter: "ማእከል ወጻኢታት",
  reciver: "ተቐባሊ",
  Date: "ዕለት",
  FixedAssetCosting: "ጸብጻብ ወጻኢታት ቀዋሚ ንብረት",
  CostType: "ዓይነት ወጻኢታት",
  Treasuryexpert: "ክኢላ ካዝና",
  Model22U: "መርኣያ 22ሀ",
  CompanyFullName: "ቤት ፅሕፈት ምምሕዳር ድሬዳዋ",
  Comment: "ርእይቶ",
  Quantity: "መጠን",
  Home: "ገዛ",
  loginText: "በጃኹም፣ ንኽትቅጽሉን ንኹሉ ኣገልግሎታትና ንኽትረኽቡን ናይ መእተዊ መረጋገጺ ሃቡ።",
  UserName: "ስም ተጠቃሚ",
  Password: "መሕለፊ ቓል",
  buttonText: "መእተዊ",
  Company: "ምምሕዳር ድሬዳዋ",
  Software: "ስርዓት ምሕደራ ንብረት",
  LNG: "ቋንቋ",
  Stock: "Stock",
  Information: "ሓበሬታ",
  Employee: "ሰራሕተኛ",
  pro: "ንብረት",
  Property: "ሓበሬታ ንብረት",
  propertyI: "ምዝገባ ንብረት",
  Income: "ኣታዊ",
  Fixed: "ቀዋሚ ንብረት",
  PropertyII: "ብርቂ ንብረት",
  propertyIII: "ኣብ ጥቕሚ ዝወዓለ ንብረት",
  Adjustment: "ምትዕርራይ",
  Cost: "ዋጋ",
  Setting: "ምምላእ",
  Manual: "ናይ ኢድ",
  InformationRegister: "ሓበሬታ ምምዝጋብ",
  CategorySource: "ምድብ ምንጪ ምወላ",
  IdentificationNumber: "መለለዪ ቁጽሪ",
  PropertyInventory: "ንብረት ዝርዝር",
  InventoryFixedAssets: "ዝርዝር ንብረት ቀዋሚ ንብረት",
  FAOU: "ቀዋሚ ንብረት ተጠቀምቲ",
  FAOUIC: "ቀዋሚ ንብረት ተጠቀምቲ I&C",
  FAOUC: "ንብረት ተጠቀምቲ ንብረት",
  FAOUS: "ቀዋሚ ንብረት ቅናሽ መጠን",
  FAOUM: "ጸብጻብ ሕሳብ ቀዋሚ ንብረት",
  OrganizationIstitution: "ትካል ውዳበ",
  Propertyclassification: "ምዕቃን ንብረት",
  Costcenters: "ማእከል ወጻኢታት",
  vechiles: "ተሽከርከርቲ",
  Details: "ዝርዝር",
  Logout: "ኣውት ኣውት",
  EmployeeList: "ዝርዝር ሓበሬታ ሰራሕተኛታት",
  NewEmployee: "ሓድሽ ሰራሕተኛ ምውሳኽ",
  NewEmployeeRegistration: "ሓድሽ ቅጥዒ ምዝገባ ሰራሕተኛ",
  Order: "ስርዓት",
  EmployeePhoto: "ስእሊ ሰራሕተኛ",
  ID: "ቁጽሪ መለለዪ መንነት",
  FullName: "ምሉእ ስም",
  Gender: "ፆታ",
  WorkClass: "ናይ ስራሕ ክፍሊ",
  WorkRoom: "ክፍሊ ስራሕ",
  Action: "ተግባር",
  Find: "ርኸብ",
  FindPlaceHolder: "ስም ሰራሕተኛ",
  FirstName: "ናይ መጀመርታ ሽም",
  MiddleName: "ማእከላይ ስም",
  LastName: "ናይ መወዳእታ ሽም",
  PhoneNumber: "ቁጽሪ ተሌፎን።",
  Mobile: "ተንቀሳቓሲ",
  Email: "ኢሜል",
  Address: "አድራሻ",
  CostCenterName: "ስም ማእከል ወጻኢታት",
  CostCenters: "ማእከል ወጻኢታት ምረጽ",
  WorkPlaceName: "ስም ናይ ስራሕ ቦታ",
  WorkPostion: "ናይ ስራሕ መርገጺ",
  Male: "ተባዕታይ",
  Female: "ኣንስተይቲ",
  Registor: "ምቑጣብ",
  Cancle: "ካንከል",
  WorkPlaces: "ናይ ስራሕ ቦታ ምረጽ",
  NewPropertyRegistration: "ምዝገባ ሓድሽ ንብረት",
  Propertycategory: "ምድብ ንብረት",
  PropertySubcategory: "ንብረት ንኡስ ምድብ",
  PropertyType: "ዓይነት ንብረት",
  PropertyCode: "ሕጊ ንብረት",
  IdentityNumber: "መለለዪ ንብረት",
  Model: "መርኣያ",
  ShelfNumber: "ቁጽሪ መደርደሪ",
  Price: "ዋጋ",
  MinValue: "ዝተሓተ ዋጋ",
  MaxValue: "ዝለዓለ ዋጋ",
  ExpireDate: "ናይ ምውዳእ ዕለት",
  Describtion: "መግለጺ",
  ItemPicture: "ንብረት ምስሊ",
  Mesurment: "መለክዒ",
  ItemType: "ንብረት ክፍሊ",
  VechilesType: "ዓይነት ተሽከርካሪት።",
  vechilesModel: "ኣብ ዝተሰርሐ (ሞዴል)",
  VechilesYear: "ዕለት ምፍራይ",
  VechilesMoterNumber: "ቁጽሪ ሞተር",
  VechilesSilnder: "ሲሊንደር",
  VechilesChasi: "ቁጽሪ ቻሲ",
  VechilesPlateNumber: "ቁጽሪ ጻሕሊ",
  VechilesDateOfPurchase: "ዕለት ዕድጊ",
  VechilesCapacity: "ናይ ጽዕነት ዓቕሚ",
  CurrentStateOfVechile: "ህሉው ኩነታት እታ ተሽከርካሪት",
  VechileOwenerIdNumber: "ናይ ወናኒ ካርድ መለለዪ ቁጽሪ",
  TypeofGas: "እቲ ዝጥቀመሉ ዓይነት ነዳዲ",
  NewVechilesRegistrationPage: "ገፅ ምዝገባ ሓደሽቲ ተሽከርከርቲ",
  OfficeName: "ስም ቤት ጽሕፈት",
  OfficeList: "ዝርዝር ቤት ፅሕፈት",
  AddNewOffice: "ሓድሽ ቤት ጽሕፈት ምውሳኽ",
  PropertyMList: "ዝርዝር መለክዒ ንብረት",
  NewPropertyMList: "ሓድሽ ክፍሊ ምዝገባ",
  Name: "ምደባ ስም",
  Code: "ኮድ",
  Description: "መግለፂ",
  ID: "ID",
  StokeMain: "ስቶክ",
  StokeMainList: "ዝርዝር ስቶክ",
  StokeMainReg: "ሓድሽ ስቶክ ምውሳኽ",
  StokeName: "ስም ምድጃ",
  StokeDesc: "መግለፂ",
  Type: "ዓይነት",
  subStoke: "ንኡስ ምደባ ስቶክ",
  stokeMeasurment: "መለክዒ",
};

export const TranslationSo = {
  RegisterdDepartmentType: "Nooca Liiska Waaxda",
  NewDepartmentType: "Kudar Nooca Waaxda Cusub",
  NewDepartment: "Kudar Waaxda Cusub",
  RegisterdDepartment: "Liiska Waaxda",
  DepartmentType: "Nooca Waaxda",
  Department: "Waaxda",
  Office: "Xafiiska",
  OfficeType: "Nooca Xafiiska",
  back: "dib",
  RegisteredDate: "Taariikhda Diwaangashan",
  CreateNew22Model: "Samee Model Cusub 22L",
  AccountsPayableReceipt:
    "Qaabka Rasiidka Xisaabaadka La Bixin Karo 22L Faahfaahin",
  deliverer: "Bixiyaha",
  FileNumber: "Lambarka Faylka",
  CostCenter: "Xarunta Qiimaha",
  reciver: "qaataha",
  Date: "Taariikhda",
  FixedAssetCosting: "Warbixinta Kharashka Hantida Go'an",
  CostType: "Nooca Qiimaha",
  Treasuryexpert: "Khabiirka Khasnadda",
  Model22U: "Qaabka 22A",
  CompanyFullName: "Xafiiska Maamulka Diridhaba",
  Comment: "Faallo",
  Quantity: "Tirada",
  Home: "Guriga",
  Employee: "Shaqaale",
  loginText:
    "Fadlan, bixi aqoonsiga gelitaanka si aad u sii waddo oo aad u hesho dhammaan adeegyadayada",
  UserName: "Magaca isticmaalaha",
  Password: "Furaha",
  buttonText: "Soo gal",
  Company: "Maamulka Diridhaba",
  Software: "Nidaamka maamulka hantida",
  Home: "Guriga",
  LNG: "luqadda",
  Stock: "Kaydka",
  Information: "Xog",
  Employee: "Shaqaale",
  Property: "Macluumaadka Hantida",
  propertyI: "Diiwaangelinta Hantida",
  Income: "Dakhliga",
  Fixed: "Hanti go'an",
  PropertyII: "Shay naadir ah",
  propertyIII: "Habboon loo Isticmaalay",
  Adjustment: "toosinta",
  Cost: "Qiimaha",
  Setting: "Dejinta",
  Manual: "Buugga",
  InformationRegister: "Diiwaangeli macluumaadka",
  CategorySource: "Qaybta maalgelinta isha",
  IdentificationNumber: "Lambarka aqoonsiga",
  PropertyInventory: "Liiska Hantida",
  InventoryFixedAssets: "Hantida go'an ee alaabada",
  FAOU: "Hantida go'an ee isticmaalayaasha",
  FAOUIC: "Hantida go'an ee isticmaalayaasha I&C",
  FAOUC: "Hantida isticmaalayaasha alaabada",
  FAOUS: "Qiimaha dhimista hantida go'an",
  FAOUM: "Warbixinta xisaabta hantida go'an",
  OrganizationIstitution: "Hay'adda Ururka",
  Propertyclassification: "Qiyaasta hantida",
  Costcenters: "Xarunta Qiimaha",
  vechiles: "Gawaarida",
  Details: "Faahfaahin",
  Logout: "Ka bax",
  EmployeeList: "Liiska Macluumaadka Shaqaalaha",
  NewEmployee: "Kudar Shaqaale Cusub",
  NewEmployeeRegistration: "Foomka Diiwaangelinta Shaqaalaha Cusub",
  Order: "Dalbo",
  EmployeePhoto: "Sawirka Shaqaalaha",
  ID: "Lambarka aqoonsiga",
  FullName: "Magaca buuxa",
  Gender: "Jinsiga",
  WorkClass: "Heerka Shaqada",
  WorkRoom: "Qolka Shaqada",
  Action: "Hawlaha",
  Find: "Hel",
  FindPlaceHolder: "Magaca Shaqaalaha",
  FirstName: "Magaca hore",
  MiddleName: "Magaca dhexe",
  LastName: "Magaca Dambe",
  PhoneNumber: "lambarka taleefanka",
  Mobile: "telefoonka gacanta",
  Email: "iimaylka",
  Address: "Cinwaanka",
  CostCenterName: "Magaca Xarunta Qiimaha",
  CostCenters: "Dooro Xarunta Qiimaha",
  WorkPlaceName: "Magaca Goobta Shaqada",
  WorkPostion: "Booska shaqada",
  Male: "Lab",
  Female: "Dheddig",
  Registor: "Badbaadin",
  Cancle: "Cancle",
  WorkPlaces: "Dooro Goobta Shaqada",
  NewPropertyRegistration: "Diiwaangelinta Hantida Cusub",
  Propertycategory: "Qaybta Hantida",
  PropertySubcategory: "Qayb-hoosaadka Hantida",
  PropertyType: "Nooca Hantida",
  PropertyCode: "Xeerka Hantida",
  IdentityNumber: "Aqoonsiga hantida",
  Model: "Qaabka",
  ShelfNumber: "Lambarka shelf",
  Price: "Qiimo",
  MinValue: "Qiimaha ugu yar",
  MaxValue: "Qiimaha ugu badan",
  ExpireDate: "Taariikhda uu dhacayo",
  Describtion: "Sharaxaada",
  ItemPicture: "Sawirka Hantida",
  Mesurment: "Cabbirka",
  ItemType: "Heerka hantida",
  VechilesType: "Nooca baabuurka",
  vechilesModel: "Lagu Sameeyay (Model)",
  VechilesYear: "Taariikhda la soo saaray",
  VechilesMoterNumber: "Nambarka mishiinka",
  VechilesSilnder: "Silinder",
  VechilesChasi: "Nambarka chassis",
  VechilesPlateNumber: "Lambarka saxanka",
  VechilesDateOfPurchase: "Taariikhda iibsashada",
  VechilesCapacity: "Awoodda culeyska",
  CurrentStateOfVechile: "Xaalada Gaadhigu Hadda",
  VechileOwenerIdNumber: "Lambarka Aqoonsiga Kaadhka Mulkiilaha",
  TypeofGas: "Nooca shidaalka la isticmaalo",
  NewVechilesRegistrationPage: "Bogga Diiwaangelinta Baabuurta Cusub",
  OfficeName: "Magaca Xafiiska",
  Code: "Koodhka",
  OfficeList: "Liiska Xafiiska",
  AddNewOffice: "Kudar Xafiis Cusub",
  PropertyMList: "Liiska Qiyaasta Hantida",
  NewPropertyMList: "Diiwaanka fasalka cusub",
  Name: "Magaca Kala-saarista",
  Description: "Sharaxaada",
  StokeMain: "Stoke",
  StokeMainList: "Liiska Stoke",
  StokeMainReg: "Ku dar kayd cusub",
  StokeName: "Magaca foornada",
  StokeDesc: "Sharaxaada",
  Type: "Nooca",
  subStoke: "Qayb-hoosaadka saamiyada",
  stokeMeasurment: "Cabbirka",
};
